name: Deploy Frontend
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Docker login
              run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            - name: Build image
              run: docker build -t kishorrvcmvit/react-frontend-gh -f Dockerfile.dev .

            - name: Run tests
              run: docker run -e CI=true kishorrvcmvit/react-frontend-gh npm run test

            - name: Deploy to EB
              run: echo "ToDo EB Deploy"
