name: Deploy Frontend
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Docker login
              run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            - name: Build image
              run: docker build -t kishorrvcmvit/react-frontend-gh -f Dockerfile.dev .

            # - name: Run production tests
            #   run: docker run --target builder -e CI=true kishorrvcmvit/react-frontend-gh npm run test

            - name: Run tests
              run: docker run -e CI=true kishorrvcmvit/react-frontend-gh npm run test -- --coverage

            # - name: Run dev server
            #   run: docker run -e CI=true kishorrvcmvit/react-frontend-gh npm test

            - name: Generate deployment package
              run: zip -r deploy.zip . -x '*.git*'

            - name: Deploy to EB
              uses: einaregilsson/beanstalk-deploy@v18
              with:
                aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
                aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
                application_name: "react-gh-app"
                environment_name: "React-gh-app-env"
                version_label: "github-actions-${{ github.run_id }}"
                region: "us-east-1"
                existing_bucket_name: "elasticbeanstalk-react-gh-s3"
                deployment_package: "deploy.zip"
